let words = [
    "apple", "block", "charm", "daisy", "eagle",
    "flute", "grape", "hound", "igloo", "jelly",
    "kiosk", "lemon", "maple", "novel", "oasis",
    "piano", "quilt", "rhyme", "salty", "teeth",
    "umbra", "vixen", "waltz", "xylog", "yacht",
    "zebra", "abode", "baker", "cedar", "dolph",
    "eject", "ferry", "gland", "hinge", "input",
    "joker", "knead", "lunch", "micro", "nymph",
    "opera", "plumb", "quake", "recur", "sweat",
    "tulip", "usage", "vault", "wound", "xerox",
    "youth", "zebra", "acute", "blend", "candy",
    "drape", "elbow", "flask", "glove", "hymen",
    "icing", "joust", "knots", "level", "mixer",
    "nexus", "ozone", "prank", "quiet", "renal",
    "shade", "tiger", "umbel", "vigor", "wages",
    "xenon", "yearn", "zesty", "agile", "bison",
    "cobra", "diner", "evoke", "fiery", "glyph",
    "hatch", "irate", "juicy", "kneel", "latch",
    "marsh", "novel", "orbit", "plank", "quack",
    "raise", "shark", "tulip", "upset", "viral",
    "witty", "xylon", "young", "zebra", "acorn",
    "briar", "crisp", "dozen", "ebony", "flute",
    "gauge", "havoc", "inert", "joker", "knead",
    "lunar", "mango", "nymph", "ocean", "peach",
    "quilt", "rugby", "silky", "tease", "ultra",
    "vocal", "wedge", "xerox", "yield", "zesty",
    "amigo", "bongo", "chime", "drain", "emote",
    "fable", "gypsy", "heart", "index", "jumbo",
    "koala", "lemon", "melon", "noble", "oasis",
    "piano", "query", "rugby", "savor", "token",
    "unity", "value", "witty", "xenon", "yield",
    "zebra"
];

let word = words[Math.floor(Math.random() * words.length)];